import Onyx from 'react-native-onyx';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import waitForBatchedUpdatesWithAct from '../utils/waitForBatchedUpdatesWithAct';

// The early-return at HybridApp.ts:82-84 gates the entire sign-in path
// behind CONFIG.IS_HYBRID_APP. On web (which Jest runs as), this resolves
// to false, so we override it here for the suite.
jest.mock('@src/CONFIG', () => {
    const actual = jest.requireActual<{default: Record<string, unknown>}>('@src/CONFIG').default;
    return {
        // eslint-disable-next-line @typescript-eslint/naming-convention
        __esModule: true,
        default: {...actual, IS_HYBRID_APP: true},
    };
});

// HybridApp.ts reads the user's email via this helper as part of the
// signInToOldDot payload. Stub it so the call shape is deterministic.
jest.mock('@libs/Network/NetworkStore', () => ({
    getCurrentUserEmail: () => 'test@example.com',
}));

// Side-effect actions invoked inside signInToOldDotAndChooseExperience
// after the native sign-in call. Stubbed so the .then chain resolves
// without touching real Onyx writes.
jest.mock('@libs/actions/HybridApp', () => ({
    setReadyToShowAuthScreens: jest.fn(),
    setUseNewDotSignInPage: jest.fn(() => Promise.resolve()),
    closeReactNativeApp: jest.fn(),
}));

Onyx.init({keys: ONYXKEYS});

type HybridAppModuleWithSignIn = {
    signInToOldDot: (params: {policyID: string; email: string; authToken: string; autoGeneratedLogin: string; autoGeneratedPassword: string; signingInWithSAML: boolean}) => void;
};

describe('HybridApp NVP_ACTIVE_POLICY_ID sign-in re-trigger (issue #91398)', () => {
    const {default: HybridAppModule} = require('@expensify/react-native-hybrid-app') as {default: HybridAppModuleWithSignIn};
    let signInToOldDotSpy: jest.SpiedFunction<HybridAppModuleWithSignIn['signInToOldDot']>;

    beforeAll(() => {
        // Importing the side-effect module registers all six Onyx
        // subscriptions defined at HybridApp.ts:23-69. Done once for the
        // suite; subscriptions persist across tests and re-fire whenever
        // their key changes.
        require('@libs/HybridApp');
    });

    beforeEach(async () => {
        signInToOldDotSpy = jest.spyOn(HybridAppModule, 'signInToOldDot').mockImplementation(() => {});
        await Onyx.clear();
        await waitForBatchedUpdatesWithAct();
        signInToOldDotSpy.mockClear();
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    it('re-fires signInToOldDot when NVP_ACTIVE_POLICY_ID hydrates after every other prerequisite', async () => {
        // Reproduce the production race: every other Onyx key needed by
        // signInToOldDotAndChooseExperience arrives before
        // NVP_ACTIVE_POLICY_ID. One of these earlier subscriptions will
        // fire the sign-in with an empty policyID (the pre-fix behavior).
        await Onyx.multiSet({
            [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true, signingInWithSAML: false},
            [ONYXKEYS.NVP_TRY_NEW_DOT]: {classicRedirect: {dismissed: true}},
            [ONYXKEYS.CREDENTIALS]: {autoGeneratedLogin: 'login', autoGeneratedPassword: 'pw'},
            [ONYXKEYS.ACCOUNT]: {requiresTwoFactorAuth: false, needsTwoFactorAuthSetup: false},
            [ONYXKEYS.SESSION]: {authToken: 'auth-token', authTokenType: CONST.AUTH_TOKEN_TYPES.SUPPORT},
        });
        await waitForBatchedUpdatesWithAct();

        // Sanity check: sign-in already fired once with an empty policy
        // because activePolicyID was undefined at the time.
        expect(signInToOldDotSpy).toHaveBeenCalled();
        const initialCall = signInToOldDotSpy.mock.calls.at(-1)?.[0];
        expect(initialCall?.policyID).toBe('');

        signInToOldDotSpy.mockClear();

        // Now the late-arriving active policy ID hydrates. With the fix
        // at HybridApp.ts:64-70 the subscription re-runs sign-in; without
        // the fix it only updates the module-local variable and
        // signInToOldDot is never called again with the real policyID.
        await Onyx.set(ONYXKEYS.NVP_ACTIVE_POLICY_ID, 'POLICY_123');
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).toHaveBeenCalledTimes(1);
        expect(signInToOldDotSpy.mock.calls.at(0)?.[0].policyID).toBe('POLICY_123');
    });

    it('does not bypass prerequisite guards when only NVP_ACTIVE_POLICY_ID is present', async () => {
        // Session/credentials/account/hybrid-app are all absent — the
        // existing early-returns inside signInToOldDotAndChooseExperience
        // must still block sign-in even though the new subscription now
        // triggers the function.
        await Onyx.set(ONYXKEYS.NVP_ACTIVE_POLICY_ID, 'POLICY_456');
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).not.toHaveBeenCalled();
    });
});
